### ISSUE TITLE
Fix readthedocs instructions and setup

### ISSUE THREAD

**Issue by shntnu** [0x00B1/persistence#117]
- [x] Update the [wiki](https://github.com/cytomining/cytominer-database/wiki/Release) with instructions to update [`doc/conf.py`](https://github.com/cytomining/cytominer-database/blob/61af4a4ce8464616de9e7c057db366beda67c70a/doc/conf.py#L49-L61) as needed
- [x] The webhooks seem to be set up incorrectly. E.g. currently 0.3.3 doesn't show up in https://readthedocs.org/projects/cytominer-database/versions/ although a request was made https://readthedocs.org/dashboard/cytominer-database/integrations/14868/exchange/07e556e0-13ac-4364-b848-41c2778f1506/. I had disabled `Push` in https://github.com/cytomining/cytominer-database/settings/hooks/16432057 but maybe that's required?

**Comment by gwaybio** [comment]
important autobuild command: `python setup.py build_sphinx --build-dir doc/_build`

**Comment by gwaybio** [comment]
following instructions on [`readthedocs` github webhook integration](https://docs.readthedocs.io/en/stable/webhooks.html#github), I added the following:

* Select Let me select individual events, and mark Branch or tag creation, Branch or tag deletion and Pushes events

**Comment by gwaybio** [comment]
updated the wiki [here](https://github.com/cytomining/cytominer-database/wiki/Release/_compare/f7ec1238c45caf9a54b2f7c5bd0e9648698f2bbf...61b39f2afb370d911203e303c1c2f4e3323cc3a6).

**Comment by gwaybio** [comment]
> Update the wiki with instructions to update doc/conf.py as needed

note that changes to `setup.cfg` override variables set in `conf.py`. No need to update `conf.py`. See https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

**Comment by gwaybio** [comment]
After merging in #118, we now receive a [build failed error](https://readthedocs.org/projects/cytominer-database/builds/10131544/):

```bash
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/six.py", line 712, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/checkouts/latest/doc/conf.py", line 140, in <module>
    [author], 1)
NameError: name 'author' is not defined


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/envs/latest/lib/python2.7/site-packages/six.py", line 712, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/cytominer-database/checkouts/latest/doc/conf.py", line 140, in <module>
    [author], 1)
NameError: name 'author' is not defined
```

**Comment by gwaybio** [comment]
Looks like [this is the culprit](https://github.com/cytomining/cytominer-database/pull/118/files#diff-684a0ceb2878d48b19612ca360e277efL52).

We removed the "author" field from `conf.py` and did not add one back to `setup.cfg`. I will hotfix

**Comment by gwaybio** [comment]
Looks like #119 did not fix ☹️ 

I will re-add `author` to `conf.py` only to have it overwritten by `setup.cfg`

**Comment by gwaybio** [comment]
Building locally, I got this error:

```bash
running build_sphinx
error: error in setup.cfg: command 'BuildDoc' has no such option 'author'
```

So, to reduce the amount of time spent on this issue, I just added instructions to update the `doc/conf.py` file [here](https://github.com/cytomining/cytominer-database/wiki/Release/_compare/61b39f2afb370d911203e303c1c2f4e3323cc3a6...f0e2b0a37a88667dfe34673d29a29cb18dd3df28). PR incoming

**Comment by shntnu** [comment]
Thanks @gwaygenomics for figuring all this out! I tested in a clean environment and this works fine.

I have deleted the documentation instructions in [Development](https://github.com/cytomining/cytominer-database/wiki/Development/_compare/c0d54d84955d9492029ce143e128c9577498beb8...2b4c4e9a08aa943e4f86581ed2c4a6de1b774a82) wiki because that was confusing (and gave wrong results).
