### ISSUE TITLE
Fix docstrings for ingest?

### ISSUE THREAD

**Issue by shntnu** [0x00B1/persistence#23]
I did 
```
sphinx-apidoc . -o doc/
cd doc
make html
``` 
and got this error
```
Running Sphinx v1.5.2
loading translations [en]... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] setup
/Users/shsingh/tmp/cytominer-database/doc/cytominer_database.rst:10: WARNING: autodoc: failed to import module 'cytominer_database.ingest'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/envs/cyto351/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/Users/shsingh/tmp/cytominer-database/cytominer_database/ingest.py", line 157, in <module>
    version=pkg_resources.get_distribution("cytominer_database").version
  File "/usr/local/var/pyenv/versions/3.5.1/envs/cyto351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 552, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/cyto351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 426, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/var/pyenv/versions/3.5.1/envs/cyto351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/var/pyenv/versions/3.5.1/envs/cyto351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cytominer_database' distribution was not found and is required by the application
/Users/shsingh/tmp/cytominer-database/doc/setup.rst:4: WARNING: autodoc: failed to import module 'setup'; the module executes module level statement and it might call sys.exit().
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/shsingh/tmp/cytominer-database/doc/modules.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] setup
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/Users/shsingh/tmp/cytominer-database/doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 4 warnings.
```

**Comment by mcquin** [comment]
Resolved <COMMIT_PLZ>
